### ISSUE TITLE
test: RuntimeError: NetCDF: String match to name in use

### ISSUE THREAD

**Issue by 510781109** [peckhams/topoflow36#12]
Imported netCDF4 version: 1.5.7
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\tf36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\__main__.py", line 24, in <module>
    main()
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\__main__.py", line 20, in main
    cfg_directory=args.cfg_directory, driver_comp_name=args.driver_comp_name )
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\framework\tests\test_framework.py", line 75, in topoflow_test
    time_interp_method=time_interp_method )
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\framework\emeli.py", line 1338, in run_model
    OK = self.initialize_comp_set( REPORT=False )
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\framework\emeli.py", line 1837, in initialize_comp_set
    self.initialize( provider_name, cfg_file )
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\framework\emeli.py", line 1015, in initialize
    mode=mode )
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\components\channels_base.py", line 785, in initialize
    self.open_output_files()
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\components\channels_base.py", line 3799, in open_output_files
    units_name='m^3/s')
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\utils\model_output.py", line 386, in open_new_ts_file
    "OVERWRITE_OK=self.OVERWRITE_OK)" )  # (2022-02-16)
  File "<string>", line 1, in <module>
  File "E:\PYTHON_WORKSTATION\topoflow36-master\topoflow\utils\ncts_files.py", line 598, in open_new_file
    var = ncts_unit.createVariable(var_name, dtype_codes[k], ("time",))
  File "src\netCDF4\_netCDF4.pyx", line 2748, in netCDF4._netCDF4.Dataset.createVariable
  File "src\netCDF4\_netCDF4.pyx", line 3808, in netCDF4._netCDF4.Variable.__init__
  File "src\netCDF4\_netCDF4.pyx", line 1927, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: String match to name in use

**Comment by 510781109** [comment]
Something wrong within an input file.
