### ISSUE TITLE
Unable to run Erode_Test

### ISSUE THREAD

**Issue by mosoriob** [peckhams/topoflow36#4]
Using the commit `39959ebf34a0f36b47d05f157cec6d53f044f847`

I have installed the dependencies

```bash
conda install nb_conda
conda install gdal
conda install matplotlib
conda install imageio
pip install imageio-ffmpeg  (an imageio extension)

cd TF36_DIR
pip install .
```

```bash
(base) root@827c320f5cf0:/topoflow36/topoflow/examples# /opt/conda/bin/python3  -m topoflow --cfg_directory Erode_Test --cfg_prefix Test
Importing TopoFlow 3.6 packages:
   topoflow.utils
   topoflow.utils.tests
   topoflow.components
   topoflow.components.tests
   topoflow.framework
   topoflow.framework.tests

Importing TopoFlow 3.6 packages:
   topoflow.utils
   topoflow.utils.tests
   topoflow.components
   topoflow.components.tests
   topoflow.framework
   topoflow.framework.tests

EMELI: Reading info from provider_file:
    /topoflow36/topoflow/examples/Erode_Test/Test_providers.txt
EMELI: Reading info from comp_repo_file:
    /opt/conda/lib/python3.7/site-packages/topoflow/framework/component_repository.xml

EMELI: Instantiated component: erode_d8_global
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/topoflow/__main__.py", line 24, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/topoflow/__main__.py", line 20, in main
    cfg_directory=args.cfg_directory, driver_comp_name=args.driver_comp_name )
  File "/opt/conda/lib/python3.7/site-packages/topoflow/framework/tests/test_framework.py", line 75, in topoflow_test
    time_interp_method=time_interp_method )
  File "/opt/conda/lib/python3.7/site-packages/topoflow/framework/emeli.py", line 1310, in run_model
    driver = self.comp_set[ driver_comp_name ]
KeyError: 'topoflow_driver'
(base) root@827c320f5cf0:/topoflow36/topoflow/examples# /opt/conda/bin/python3  -m topoflow --cfg_directory Erode_Test --cfg_prefix Test
Importing TopoFlow 3.6 packages:
   topoflow.utils
   topoflow.utils.tests
   topoflow.components
   topoflow.components.tests
   topoflow.framework
   topoflow.framework.tests

Importing TopoFlow 3.6 packages:
   topoflow.utils
   topoflow.utils.tests
   topoflow.components
   topoflow.components.tests
   topoflow.framework
   topoflow.framework.tests

EMELI: Reading info from provider_file:
    /topoflow36/topoflow/examples/Erode_Test/Test_providers.txt
EMELI: Reading info from comp_repo_file:
    /opt/conda/lib/python3.7/site-packages/topoflow/framework/component_repository.xml

EMELI: Instantiated component: erode_d8_global
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/topoflow/__main__.py", line 24, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/topoflow/__main__.py", line 20, in main
    cfg_directory=args.cfg_directory, driver_comp_name=args.driver_comp_name )
  File "/opt/conda/lib/python3.7/site-packages/topoflow/framework/tests/test_framework.py", line 75, in topoflow_test
    time_interp_method=time_interp_method )
  File "/opt/conda/lib/python3.7/site-packages/topoflow/framework/emeli.py", line 1310, in run_model
    driver = self.comp_set[ driver_comp_name ]
KeyError: 'topoflow_driver'
```

**Comment by mosoriob** [comment]
```bash
(base) root@827c320f5cf0:/# conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
asn1crypto                1.3.0                    py37_0
attrs                     19.3.0                     py_0
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.6.24                     0
cairo                     1.14.12              h8948797_3
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h2e261b9_0
cfitsio                   3.470                hb7c8383_2
cftime                    1.2.1                    pypi_0    pypi
cfunits                   3.2.9                    pypi_0    pypi
chardet                   3.0.4                 py37_1003
conda                     4.8.3                    py37_0
conda-package-handling    1.6.0            py37h7b6447c_0
cryptography              2.8              py37h1ba5d50_0
curl                      7.67.0               hbc83047_0
cycler                    0.10.0                   py37_0
dbus                      1.13.16              hb2f20db_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
expat                     2.2.9                he6710b0_2
fontconfig                2.13.0               h9420a91_0
freetype                  2.10.2               h5ab3b9f_0
freexl                    1.0.5                h14c3975_0
gdal                      3.0.2            py37hbb2a789_0
geos                      3.8.0                he6710b0_0
geotiff                   1.5.1                h21e8280_1
giflib                    5.1.4                h14c3975_1
glib                      2.63.1               h5a9c865_0
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.10.4               hb1b8bf9_0
icu                       58.2                 he6710b0_3
idna                      2.8                      py37_0
imageio                   2.9.0                      py_0
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2020.1                      217
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.16.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.17.2                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   h024ee3a_2
json-c                    0.13.1               h1bed415_0
jsonschema                3.2.0                    py37_1
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
kealib                    1.4.7                hd0c454d_6
kiwisolver                1.2.0            py37hfd86e86_0
krb5                      1.16.4               h173b8e3_0
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libboost                  1.67.0               h46d08c1_4
libcurl                   7.67.0               h20c2e04_0
libdap4                   3.19.1               h6ec2957_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgdal                   3.0.2                h27ab9cc_0
libgfortran-ng            7.3.0                hdf63c60_0
libkml                    1.3.0                h590aaf7_4
libnetcdf                 4.6.1                h11d0813_2
libpng                    1.6.37               hbc83047_0
libpq                     11.2                 h20c2e04_0
libsodium                 1.0.18               h7b6447c_0
libspatialite             4.3.0a               h793db0d_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.9                hea5a465_1
lz4-c                     1.8.1.2              h14c3975_0
markupsafe                1.1.1            py37h14c3975_1
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py37hef1b27d_0
mistune                   0.8.4           py37h14c3975_1001
mkl                       2020.1                      217
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.1.0            py37h23d657b_0
mkl_random                1.1.1            py37h0573a6f_0
nb_conda                  2.2.1                    py37_0
nb_conda_kernels          2.2.3                    py37_0
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
ncurses                   6.2                  he6710b0_0
netcdf4                   1.5.4                    pypi_0    pypi
notebook                  6.0.3                    py37_0
numpy                     1.19.1           py37hbc911f0_0
numpy-base                1.19.1           py37hfa32c7d_0
olefile                   0.46                     py37_0
openjpeg                  2.3.0                h05c96fa_1
openssl                   1.1.1g               h7b6447c_0
packaging                 20.4                       py_0
pandoc                    2.10                          0
pandocfilters             1.4.2                    py37_1
parso                     0.7.0                      py_0
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0                    py37_1
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hb39fc2d_0
pip                       20.0.2                   py37_1
pixman                    0.40.0               h7b6447c_0
poppler                   0.65.0               h581218d_1
poppler-data              0.4.9                         0
postgresql                11.2                 h20c2e04_0
proj                      6.2.1                haa6030c_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
ptyprocess                0.6.0                    py37_0
pycosat                   0.6.3            py37h7b6447c_0
pycparser                 2.19                     py37_0
pygments                  2.6.1                      py_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.16.0           py37h7b6447c_0
pysocks                   1.7.1                    py37_0
python                    3.7.6                h0371630_2
python-dateutil           2.8.1                      py_0
pyzmq                     19.0.1           py37he6710b0_1
qt                        5.9.7                h5867ecd_1
readline                  7.0                  h7b6447c_5
requests                  2.22.0                   py37_1
ruamel_yaml               0.15.87          py37h7b6447c_0
scipy                     1.5.2                    pypi_0    pypi
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               h7b6447c_0
tbb                       2018.0.5             h6bb024c_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tiledb                    1.6.3                h1fb8f14_0
tk                        8.6.10               hbc83047_0
topoflow                  3.6                      pypi_0    pypi
tornado                   6.0.4            py37h7b6447c_1
tqdm                      4.42.1                     py_0
traitlets                 4.3.3                    py37_0
urllib3                   1.25.8                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
xerces-c                  3.2.2                h780794e_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.2                he6710b0_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```

**Comment by 510781109** [comment]
driver_comp_name should be set to  erode_d8_global
